### PR TITLE
Format Time values correctly in where conditions

### LINKED ISSUE #25: [BUG] `Time` is not handled correctly in `.where`
**Describe the bug**

Perhaps I'm missing something, but I couldn't find a way to use a ~~date~~ `Time` in a query without resorting to constructing the query string manually (i.e., `Model.where("CreatedDate > #{my_date.strftime('%FT%T%:z')}")`.

Passing a `Time` as a keyword argument results in a malformed query because the date string is incorrectly formatted:

```ruby
Af::CampaignSource.where(created_date: Time.current)
```
Malformed query:
```sql
SELECT ... WHERE (CreatedDate = 2023-04-06 13:24:12 UTC)
```

Passing a `Time` as a `?` parameter value does the same thing:

```ruby
Af::CampaignSource.where("CreatedDate > ?", Time.current)
```

Malformed query:

```sql
SELECT ... WHERE (CreatedDate > 2023-04-06 13:27:10 UTC)
```

Passing a formatted string in the same way quotes the value, which is incorrect:

```ruby
Af::CampaignSource.where("CreatedDate > ?", Time.current.strftime('%FT%T%:z'))
```

Malformed query:

```sql
SELECT ... WHERE (CreatedDate > '2023-04-06T13:30:59+00:00')
/*
Error:
FROM Campaign_source__c WHERE (CreatedDate > '2023-04-06T13:30:59+00:00')
ERROR at Row:1:Column:226
value of filter criterion for field 'CreatedDate' must be of type dateTime and should not be enclosed in quotes
*/
```

**Expected behavior**

I would expect `.where` to produce a correctly formatted query when I pass a date value (a `Date`, `DateTime`, or `Time`) as a keyword argument or a `?` parameter value.  For example, this:

```ruby
Af::CampaignSource.where("CreatedDate > ?", Time.current)
```

should generate this:

```sql
SELECT ... WHERE (CreatedDate > 2023-04-06T13:43:51+00:00)
```

[__Salesforce reference__](https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_dateformats.htm)

### PR DESCRIPTION
**Pull request by rferg**
Fixes #25

Also added tests for other date types.  `Date` and `DateTime` already worked because `#to_s` [returns the ISO 8601 format](https://ruby-doc.org/stdlib-2.5.1/libdoc/date/rdoc/Date.html#method-i-to_s) for those.  `Time#to_s`, however, adds incorrect spaces and time zone indicators that creates malformed SOQL queries.

### CODE REVIEW

File: lib/active_force/active_query.rb [hunk 1]
```diff
@@ -165,6 +165,8 @@ def enclose_value value
         "'#{quote_string(value)}'"
       when NilClass
         'NULL'
+      when Time
```
Comment (luminous14) [inline lib/active_force/active_query.rb:168]: Should this also account for `DateTime`?

Comment (luminous14) [reply lib/active_force/active_query.rb:168]: Never mind, I just noticed the comment.

**Review by JeffLuckett — APPROVED** [review]
