### PR TITLE
Raise `UnknownAttributeError` if `.where` is given invalid attribute names

### LINKED ISSUE #26: [BUG] Invalid keys in `.where` are silently omitted from the generated query
**Describe the bug**

If I run the following, when `:invalid` is not a field on `Model`:

```ruby
Model.where(invalid: 1)
```

It generates SOQL like this:

```sql
SELECT ... FROM Model__c WHERE ( = 1)
```

Which results in an error like this:

```
FROM Model__c WHERE ( = 1)
ERROR at Row:1:Column:226
unexpected token: '='
```

This can be difficult to troubleshoot, especially when the query is complicated and has several filter conditions.

**Expected behavior**

We need a more informative error.  Either ActiveForce should raise an error when it fails to find a field matching that key or the generated SOQL should just include the incorrect field name.  This is what ActiveRecord does, delegating the query validation to the DB.  In the case described above, SF would return an error like the following if we included `invalid` (i.e., `WHERE (invalid = 1)`):

```
FROM Model__c WHERE (invalid = 1)
                                 ^
ERROR at Row:1:Column:226
No such column 'invalid' on entity 'Model__c'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
``` 

This is a lot more helpful because it identifies the incorrect field.

### PR DESCRIPTION
**Pull request by rferg**
Closes #26

### CODE REVIEW

File: spec/active_force/active_query_spec.rb [hunk 1]
```diff
@@ -1,12 +1,17 @@
 require 'spec_helper'
 
+class TestSObject < ActiveForce::SObject
+  def self.decorate(records)
```
Comment (rferg) [inline spec/active_force/active_query_spec.rb:4]: There was a spec failing below when I changed `sobject` to a `class_double` because `ActiveForce::SObject` does not implement `.decorate`.  I see that this method is supposed to be something that the consumer would implement in their subclass.  This seems like a weird pattern to use with class methods.  In any case, this seemed like the least intrusive workaround so that we can get a `class_double` here that validates that this mock matches real methods.

Comment (asedge) [reply spec/active_force/active_query_spec.rb:4]: Yeah, I never fully understood why the original authors of this library did something like that but I guess we're stuck with it for now. 🤷

**Review by asedge — APPROVED** [review]
LGTM, thanks! Will leave it open for a bit to see if anyone else chimes in.
