### PR TITLE
Fixes #91. Applies scopes to eager-loaded associations when they are nested.

### LINKED ISSUE #91: [BUG] Eager loaded associations, when using nested associations, do not apply the scope
**Describe the bug**
When using `includes` to eager load associations if that association is nested, e.g. `includes(child: :grandchild)`, any scope defined on the `:child` association will not be applied.

**To Reproduce**
Use a scoped, nested association when eager loading.

**Expected behavior**
The scope is applied even when using a "nested" include

### PR DESCRIPTION
**Pull request by asedge**
I have previously fixed the eager loading of scoped associations (#67). The way the query was built when using includes with association nesting is different so it only worked if you didn't try to nest anything above it (e.g. `includes(:scoped_association)` and not `includes(scoped_association: :child)`.  I did a bit of a refactor to align them so the latter example will now work and because it's called recursively the scopes will be applied all the way down the chain.

### CODE REVIEW

File: spec/active_force/sobject/includes_spec.rb [hunk 1]
```diff
@@ -397,9 +397,41 @@ module ActiveForce
...
       end
 
+      context 'when the associations have scopes' do
+        it 'generates the correct SOQL query' do
+          soql = Blog.includes(active_posts: :impossible_comments).where(id: '123').to_s
+          expect(soql).to eq <<-SOQL.squish
+            SELECT Id, Name, Link__c,
+              (SELECT Id, Title__c, BlogId, IsActive,
+                (SELECT Id, PostId, PosterId__c, FancyPostId, Body__c
+                  FROM Comments__r WHERE (1 = 0))
```
Comment (bfrey08) [inline spec/active_force/sobject/includes_spec.rb:407]: `WHERE (1 = 0))` nice.

Comment (asedge) [reply spec/active_force/sobject/includes_spec.rb:407]: 😄 it was one of the pre-defined scopes from the original authors

**Review by bfrey08 — APPROVED** [review]
Makes sense, good stuff!

**Review by swpreethi — APPROVED** [review]
I like how you refactored the existing projection builder and re-used it in the nested projection builder thereby keeping it all to be from one place.
Great stuff !! This would help us use the nested includes more effectively . thanks 😄
